void relatorios();
void relatorios_filtro(void);
void relatorios_filtro_ativos(void);
void relatorios_filtro_inativos(void);
void servicos_atrelado_cliente(char cpf[]);
void relatorios_ordenados(void);
void relatorio_tabela(void);
void relatorio_tabela_clientes(void);
void relatorio_tabela_funcionarios(void);
void relatorio_tabela_servicos(void);